//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 19:52:32  on 19 январь 2003 г.
//
//	Generated for file: C:\Work\Palm\NR2\Game\Project\Rsc\Graphics.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Untitled"
//
//	Palm App Version:		"1.0"


//	Resource: Talt 5000
#define NeedMoreColorsAlert                       5000
#define NeedMoreColorsCloseApplication            0

//	Resource: Talt 5100
#define COLORAlert                                5100
#define COLOR_8                                   0


//	Resource: PICT 1600
#define BitmapID1600Bitmap                        1600

//	Resource: PICT 1700
#define BitmapID1700Bitmap                        1700

//	Resource: PICT 2400
#define BitmapID2400Bitmap                        2400

//	Resource: PICT 2900
#define BitmapID2900Bitmap                        2900

//	Resource: PICT 3000
#define BitmapID3000Bitmap                        3000

//	Resource: PICT 3100
#define BitmapID3100Bitmap                        3100

//	Resource: PICT 3400
#define untitledBitmap                            3400


//	Resource: tbmf 1801
#define SpeedBitmapFamily                         1801

//	Resource: tbmf 3400
#define RotateBackBitmapFamily                    3400

//	Resource: tbmf 1700
#define FPSBitmapFamily                           1700

//	Resource: tbmf 1600
#define NumbersBitmapFamily                       1600

//	Resource: tbmf 2301
#define LapBitmapFamily                           2301

//	Resource: tbmf 2400
#define SmallNumbersBitmapFamily                  2400

//	Resource: tbmf 2501
#define PositionBitmapFamily                      2501

//	Resource: tbmf 2801
#define FinalLapBitmapFamily                      2801

//	Resource: tbmf 2900
#define ThreeBitmapFamily                         2900

//	Resource: tbmf 3000
#define TwoBitmapFamily                           3000

//	Resource: tbmf 3100
#define OneBitmapFamily                           3100

//	Resource: tbmf 3201
#define GoBitmapFamily                            3201

//	Resource: tbmf 3301
#define FinishBitmapFamily                        3301

