//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 15:56:57  on 18 Äåêàáðü 2002 ã.
//
//	Generated for file: C:\Work\Palm\Flat3D\Project\Rsc\Flat3D.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Napalm Racing"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)

//	Resource: tFRM 1200
#define ConfigForm                                1200	//(Left Origin = 1, Top Origin = 1, Width = 158, Height = 158, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ConfigDoneButton                          1206	//(Left Origin = 5, Top Origin = 134, Width = 80, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define ConfigCancelButton                        1207	//(Left Origin = 92, Top Origin = 134, Width = 60, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define ConfigMuteSoundCheckbox                   1210	//(Left Origin = 80, Top Origin = 117, Width = 70, Height = 12, Usable = 0, Selected = 1, Group ID = 0, Font = Standard)
#define ConfigShowFPSCheckbox                     1214	//(Left Origin = 11, Top Origin = 117, Width = 55, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define ConfigUnnamed1202Label                    1202	//(Left Origin = 4, Top Origin = 18, Usable = 1, Font = Standard)
#define ConfigUnnamed1204Label                    1204	//(Left Origin = 6, Top Origin = 61, Usable = 1, Font = Standard)
#define ConfigUnnamed1205Label                    1205	//(Left Origin = 7, Top Origin = 33, Usable = 1, Font = Standard)
#define ConfigUnnamed1209Label                    1209	//(Left Origin = 124, Top Origin = 61, Usable = 1, Font = Standard)
#define ConfigUnnamed1211Label                    1211	//(Left Origin = 5, Top Origin = 104, Usable = 1, Font = Standard)
#define ConfigUnnamed1212Label                    1212	//(Left Origin = 6, Top Origin = 75, Usable = 1, Font = Standard)
#define ConfigUnnamed1215Label                    1215	//(Left Origin = 133, Top Origin = 104, Usable = 1, Font = Standard)
#define ConfigGraffitiPushButton                  1201	//(Left Origin = 64, Top Origin = 17, Width = 40, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define ConfigButtonsPushButton                   1203	//(Left Origin = 109, Top Origin = 17, Width = 45, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define ConfigRudderSpeedSliderControl            1208	//(Left Origin = 5, Top Origin = 44, Width = 150, Height = 15, Usable = 1, Initial Value = 1, Minimum Value = 0, Maximum Value = 8, Page Jump Amount = 1, Thumb Bitmap = 0, Background Bitmap = 0)
#define ConfigHandingSliderControl                1213	//(Left Origin = 4, Top Origin = 87, Width = 150, Height = 15, Usable = 1, Initial Value = 12, Minimum Value = 1, Maximum Value = 50, Page Jump Amount = 1, Thumb Bitmap = 0, Background Bitmap = 0)
#define ConfigGroupID                             1

//	Resource: tFRM 1300
#define TrackForm                                 1300	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define TrackBackButton                           1301	//(Left Origin = 102, Top Origin = 130, Width = 50, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define TrackLapsField                            1306	//(Left Origin = 141, Top Origin = 111, Width = 15, Height = 15, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Large, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define TrackUnnamed1302Label                     1302	//(Left Origin = 97, Top Origin = 111, Usable = 1, Font = Large)
#define TrackNameLabel                            1304	//(Left Origin = 5, Top Origin = 21, Usable = 1, Font = Bold 12)
#define TrackNamesList                            1303	//(Left Origin = 3, Top Origin = 41, Width = 90, Usable = 1, Font = Standard, Visible Items = 10)

//	Resource: tFRM 1400
#define MenuForm                                  1400	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MenuSingleRaceButton                      1401	//(Left Origin = 66, Top Origin = 25, Width = 90, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define MenuOptionsButton                         1402	//(Left Origin = 66, Top Origin = 109, Width = 90, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define MenuDemoButton                            1405	//(Left Origin = 66, Top Origin = 81, Width = 90, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define MenuChampionshipButton                    1406	//(Left Origin = 66, Top Origin = 53, Width = 90, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define MenuUnnamed1407BitMap                     2610	//(Left Origin = 0, Top Origin = 26, Bitmap Resource ID = 2610, Usable = 1)
#define MenuUnnamed1408BitMap                     2620	//(Left Origin = 0, Top Origin = 54, Bitmap Resource ID = 2620, Usable = 1)
#define MenuUnnamed1409BitMap                     2630	//(Left Origin = 0, Top Origin = 81, Bitmap Resource ID = 2630, Usable = 1)
#define MenuUnnamed1410BitMap                     2640	//(Left Origin = 0, Top Origin = 110, Bitmap Resource ID = 2640, Usable = 1)
#define MenuBuildDateLabel                        1403	//(Left Origin = 104, Top Origin = 149, Usable = 1, Font = Standard)
#define MenuUnnamed1404Label                      1404	//(Left Origin = 1, Top Origin = 149, Usable = 1, Font = Standard)

//	Resource: tFRM 1500
#define OptionsForm                               1500	//(Left Origin = 20, Top Origin = 50, Width = 120, Height = 80, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define OptionsBackButton                         1506	//(Left Origin = 31, Top Origin = 54, Width = 60, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define OptionsSmallMapCheckbox                   1512	//(Left Origin = 2, Top Origin = 19, Width = 90, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define OptionsTransparentMapCheckbox             1513	//(Left Origin = 2, Top Origin = 35, Width = 110, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)

//	Resource: tFRM 1700
#define PlayerForm                                1700	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define PlayerBackButton                          1706	//(Left Origin = 10, Top Origin = 137, Width = 50, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define PlayerNameField                           1705	//(Left Origin = 30, Top Origin = 102, Width = 110, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 60, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define PlayerUnnamed1707GraffitiShift            1707	//(Left Origin = 142, Top Origin = 142)
#define PlayerUnnamed1702Label                    1702	//(Left Origin = 13, Top Origin = 122, Usable = 1, Font = Standard)
#define PlayerUnnamed1704Label                    1704	//(Left Origin = 2, Top Origin = 103, Usable = 1, Font = Standard)
#define PlayerGraffitiPushButton                  1701	//(Left Origin = 64, Top Origin = 122, Width = 40, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define PlayerButtonsPushButton                   1703	//(Left Origin = 109, Top Origin = 122, Width = 45, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define PlayerColorSliderControl                  1708	//(Left Origin = 5, Top Origin = 83, Width = 150, Height = 15, Usable = 1, Initial Value = 0, Minimum Value = 0, Maximum Value = 10, Page Jump Amount = 1, Thumb Bitmap = 2605, Background Bitmap = 2600)
#define PlayerGroupID                             1

//	Resource: tFRM 1800
#define OpponentsForm                             1800	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define OpponentsBackButton                       1801	//(Left Origin = 10, Top Origin = 137, Width = 50, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define OpponentsUnnamed1802Label                 1802	//(Left Origin = 4, Top Origin = 24, Usable = 1, Font = Large)
#define OpponentsUnnamed1812Label                 1812	//(Left Origin = 5, Top Origin = 78, Usable = 1, Font = Large)
#define OpponentsNotPushButton                    1803	//(Left Origin = 11, Top Origin = 43, Width = 20, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define OpponentsUnnamed1804PushButton            1804	//(Left Origin = 34, Top Origin = 43, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define OpponentsUnnamed1805PushButton            1805	//(Left Origin = 49, Top Origin = 43, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define OpponentsUnnamed1806PushButton            1806	//(Left Origin = 64, Top Origin = 43, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define OpponentsUnnamed1807PushButton            1807	//(Left Origin = 79, Top Origin = 43, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define OpponentsUnnamed1808PushButton            1808	//(Left Origin = 94, Top Origin = 43, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define OpponentsUnnamed1809PushButton            1809	//(Left Origin = 109, Top Origin = 43, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define OpponentsUnnamed1810PushButton            1810	//(Left Origin = 124, Top Origin = 43, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define OpponentsEightPushButton                  1811	//(Left Origin = 139, Top Origin = 43, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define OpponentsNovicePushButton                 1813	//(Left Origin = 7, Top Origin = 100, Width = 50, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define OpponentsAmateurPushButton                1814	//(Left Origin = 61, Top Origin = 100, Width = 45, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define OpponentsMasterPushButton                 1815	//(Left Origin = 110, Top Origin = 100, Width = 45, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define OpponentsGroupID                          1
#define OpponentsGroupID2                         2

//	Resource: tFRM 1600
#define SingleRaceForm                            1600	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define SingleRaceBackButton                      1601	//(Left Origin = 10, Top Origin = 137, Width = 50, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define SingleRaceGoButton                        1602	//(Left Origin = 92, Top Origin = 137, Width = 60, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define SingleRaceUnnamed1609BitMap               2650	//(Left Origin = 60, Top Origin = 94, Bitmap Resource ID = 2650, Usable = 1)
#define SingleRaceUnnamed1610BitMap               2660	//(Left Origin = 41, Top Origin = 55, Bitmap Resource ID = 2660, Usable = 1)
#define SingleRaceUnnamed1611BitMap               2670	//(Left Origin = 46, Top Origin = 17, Bitmap Resource ID = 2670, Usable = 1)
#define SingleRaceUnnamed1603Label                1603	//(Left Origin = 5, Top Origin = 20, Usable = 1, Font = Bold 12)
#define SingleRaceUnnamed1606Label                1606	//(Left Origin = 5, Top Origin = 58, Usable = 1, Font = Bold 12)
#define SingleRaceUnnamed1608Label                1608	//(Left Origin = 1, Top Origin = 97, Usable = 1, Font = Bold 12)
#define SingleRaceTrackSelTrigger                 1604	//(Left Origin = 18, Top Origin = 37, Width = 140, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard)
#define SingleRacePlayerSelTrigger                1605	//(Left Origin = 17, Top Origin = 76, Width = 140, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard)
#define SingleRaceOpponentsSelTrigger             1607	//(Left Origin = 17, Top Origin = 115, Width = 140, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard)

//	Resource: tFRM 1900
#define RaceResultsForm                           1900	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define RaceResultsDoneButton                     1910	//(Left Origin = 49, Top Origin = 135, Width = 60, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define RaceResultsFirstLabel                     1901	//(Left Origin = 13, Top Origin = 32, Usable = 1, Font = Bold 12)
#define RaceResultsUnnamed1902Label               1902	//(Left Origin = 58, Top Origin = 52, Usable = 1, Font = Large)
#define RaceResultsUnnamed1903Label               1903	//(Left Origin = 58, Top Origin = 67, Usable = 1, Font = Large)
#define RaceResultsUnnamed1904Label               1904	//(Left Origin = 14, Top Origin = 88, Usable = 1, Font = Standard)
#define RaceResultsUnnamed1905Label               1905	//(Left Origin = 91, Top Origin = 88, Usable = 1, Font = Standard)
#define RaceResultsUnnamed1906Label               1906	//(Left Origin = 14, Top Origin = 102, Usable = 1, Font = Standard)
#define RaceResultsUnnamed1907Label               1907	//(Left Origin = 91, Top Origin = 102, Usable = 1, Font = Standard)
#define RaceResultsUnnamed1908Label               1908	//(Left Origin = 14, Top Origin = 116, Usable = 1, Font = Standard)
#define RaceResultsUnnamed1909Label               1909	//(Left Origin = 91, Top Origin = 116, Usable = 1, Font = Standard)
#define RaceResultsUnnamed1911Label               1911	//(Left Origin = 8, Top Origin = 17, Usable = 1, Font = Large)
#define RaceResultsUnnamed1912Label               1912	//(Left Origin = 8, Top Origin = 54, Usable = 1, Font = Bold)
#define RaceResultsUnnamed1913Label               1913	//(Left Origin = 8, Top Origin = 69, Usable = 1, Font = Bold)
#define RaceResultsUnnamed1914Label               1914	//(Left Origin = 3, Top Origin = 86, Usable = 1, Font = Bold 12)
#define RaceResultsUnnamed1915Label               1915	//(Left Origin = 82, Top Origin = 86, Usable = 1, Font = Bold 12)
#define RaceResultsUnnamed1916Label               1916	//(Left Origin = 3, Top Origin = 100, Usable = 1, Font = Bold 12)
#define RaceResultsUnnamed1917Label               1917	//(Left Origin = 82, Top Origin = 100, Usable = 1, Font = Bold 12)
#define RaceResultsUnnamed1918Label               1918	//(Left Origin = 3, Top Origin = 114, Usable = 1, Font = Bold 12)
#define RaceResultsUnnamed1919Label               1919	//(Left Origin = 82, Top Origin = 114, Usable = 1, Font = Bold 12)

//	Resource: tFRM 2000
#define ChampionshipForm                          2000	//(Left Origin = 0, Top Origin = 1, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ChampionshipRaceButton                    2001	//(Left Origin = 97, Top Origin = 110, Width = 60, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define ChampionshipBackButton                    2002	//(Left Origin = 97, Top Origin = 135, Width = 60, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define ChampionshipRestartButton                 2006	//(Left Origin = 99, Top Origin = 1, Width = 60, Height = 10, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define ChampionshipTrackNameLabel                2004	//(Left Origin = 20, Top Origin = 19, Usable = 1, Font = Bold 12)
#define ChampionshipTrackNLabel                   2007	//(Left Origin = 0, Top Origin = 19, Usable = 1, Font = Bold 12)
#define ChampionshipPlayersList                   2005	//(Left Origin = 6, Top Origin = 37, Width = 85, Usable = 1, Font = Standard, Visible Items = 9)
#define ChampionshipPlayerSelTrigger              2003	//(Left Origin = 5, Top Origin = 143, Width = 85, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard)

//	Resource: tFRM 2100
#define ChampsResultsForm                         2100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ChampsResultsFirstButton                  2101	//(Left Origin = 4, Top Origin = 16, Width = 150, Height = 12, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Bold 12)
#define ChampsResultsUnnamed2102Button            2102	//(Left Origin = 1, Top Origin = 43, Width = 85, Height = 12, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Large)
#define ChampsResultsUnnamed2103Button            2103	//(Left Origin = 69, Top Origin = 58, Width = 85, Height = 12, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Large)
#define ChampsResultsDoneButton                   2110	//(Left Origin = 49, Top Origin = 137, Width = 60, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define ChampsResultsUnnamed2104Label             2104	//(Left Origin = 14, Top Origin = 90, Usable = 1, Font = Standard)
#define ChampsResultsUnnamed2105Label             2105	//(Left Origin = 91, Top Origin = 90, Usable = 1, Font = Standard)
#define ChampsResultsUnnamed2106Label             2106	//(Left Origin = 14, Top Origin = 104, Usable = 1, Font = Standard)
#define ChampsResultsUnnamed2107Label             2107	//(Left Origin = 91, Top Origin = 104, Usable = 1, Font = Standard)
#define ChampsResultsUnnamed2108Label             2108	//(Left Origin = 14, Top Origin = 118, Usable = 1, Font = Standard)
#define ChampsResultsUnnamed2109Label             2109	//(Left Origin = 91, Top Origin = 118, Usable = 1, Font = Standard)
#define ChampsResultsUnnamed2114Label             2114	//(Left Origin = 3, Top Origin = 88, Usable = 1, Font = Bold 12)
#define ChampsResultsUnnamed2115Label             2115	//(Left Origin = 82, Top Origin = 88, Usable = 1, Font = Bold 12)
#define ChampsResultsUnnamed2116Label             2116	//(Left Origin = 3, Top Origin = 102, Usable = 1, Font = Bold 12)
#define ChampsResultsUnnamed2117Label             2117	//(Left Origin = 82, Top Origin = 102, Usable = 1, Font = Bold 12)
#define ChampsResultsUnnamed2118Label             2118	//(Left Origin = 3, Top Origin = 116, Usable = 1, Font = Bold 12)
#define ChampsResultsUnnamed2119Label             2119	//(Left Origin = 82, Top Origin = 116, Usable = 1, Font = Bold 12)
#define ChampsResultsUnnamed2111PushButton        2111	//(Left Origin = 44, Top Origin = 30, Width = 70, Height = 12, Usable = 1, Group ID = 0, Font = Standard)
#define ChampsResultsUnnamed2112PushButton        2112	//(Left Origin = 18, Top Origin = 58, Width = 50, Height = 12, Usable = 1, Group ID = 0, Font = Standard)
#define ChampsResultsUnnamed2113PushButton        2113	//(Left Origin = 87, Top Origin = 72, Width = 50, Height = 12, Usable = 1, Group ID = 0, Font = Standard)

//	Resource: tFRM 2200
#define NewChampsForm                             2200	//(Left Origin = 5, Top Origin = 20, Width = 150, Height = 135, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define NewChampsDoneButton                       2202	//(Left Origin = 12, Top Origin = 110, Width = 70, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define NewChampsCancelButton                     2214	//(Left Origin = 89, Top Origin = 109, Width = 50, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define NewChampsUnnamed2201Label                 2201	//(Left Origin = 6, Top Origin = 16, Usable = 1, Font = Standard)
#define NewChampsUnnamed2210Label                 2210	//(Left Origin = 4, Top Origin = 79, Usable = 1, Font = Standard)
#define NewChampsUnnamed2215Label                 2215	//(Left Origin = 4, Top Origin = 49, Usable = 1, Font = Standard)
#define NewChampsTwoLapsPushButton                2203	//(Left Origin = 22, Top Origin = 32, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define NewChampsUnnamed2204PushButton            2204	//(Left Origin = 38, Top Origin = 32, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define NewChampsUnnamed2205PushButton            2205	//(Left Origin = 54, Top Origin = 32, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define NewChampsUnnamed2206PushButton            2206	//(Left Origin = 70, Top Origin = 32, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define NewChampsUnnamed2207PushButton            2207	//(Left Origin = 86, Top Origin = 32, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define NewChampsUnnamed2208PushButton            2208	//(Left Origin = 102, Top Origin = 32, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define NewChampsUnnamed2209PushButton            2209	//(Left Origin = 118, Top Origin = 32, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define NewChampsNovicePushButton                 2211	//(Left Origin = 2, Top Origin = 92, Width = 50, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define NewChampsAmateurPushButton                2212	//(Left Origin = 55, Top Origin = 92, Width = 45, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define NewChampsMasterPushButton                 2213	//(Left Origin = 103, Top Origin = 92, Width = 45, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define NewChampsOnePushButton                    2216	//(Left Origin = 20, Top Origin = 63, Width = 12, Height = 12, Usable = 1, Group ID = 3, Font = Standard)
#define NewChampsUnnamed2217PushButton            2217	//(Left Origin = 35, Top Origin = 63, Width = 12, Height = 12, Usable = 1, Group ID = 3, Font = Standard)
#define NewChampsUnnamed2218PushButton            2218	//(Left Origin = 50, Top Origin = 63, Width = 12, Height = 12, Usable = 1, Group ID = 3, Font = Standard)
#define NewChampsUnnamed2219PushButton            2219	//(Left Origin = 65, Top Origin = 63, Width = 12, Height = 12, Usable = 1, Group ID = 3, Font = Standard)
#define NewChampsUnnamed2220PushButton            2220	//(Left Origin = 80, Top Origin = 63, Width = 12, Height = 12, Usable = 1, Group ID = 3, Font = Standard)
#define NewChampsUnnamed2221PushButton            2221	//(Left Origin = 95, Top Origin = 63, Width = 12, Height = 12, Usable = 1, Group ID = 3, Font = Standard)
#define NewChampsUnnamed2222PushButton            2222	//(Left Origin = 110, Top Origin = 63, Width = 12, Height = 12, Usable = 1, Group ID = 3, Font = Standard)
#define NewChampsEightPushButton                  2223	//(Left Origin = 125, Top Origin = 63, Width = 12, Height = 12, Usable = 1, Group ID = 3, Font = Standard)
#define NewChampsGroupID                          1
#define NewChampsGroupID2                         2
#define NewChampsGroupID3                         3


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1100
#define MsgAlert                                  1100
#define MsgOK                                     0

//	Resource: Talt 1300
#define NoTracksAlert                             1300
#define NoTracksExit                              0

//	Resource: Talt 1000
#define LANG_Alert                                1000
#define LANG_ENG                                  0


//	Resource: MBAR 1000
#define Flat3DMainMenuBar                         1000


//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsConfiguration                      1000
#define OptionsLeavetrack                         1001
#define OptionsResetcar                           1002
#define OptionsControls                           1003


//	Resource: tSTR 1000
#define ControlsString                            1000	// "Controls.    There are two possible ways to control a car: by stylus in graffiti area or by buttons (discrete).    Controls by Graffiti:           to turn  - move stylus to left or right   	accelerate - move stylus to the top part of graffi"


//	Resource: PICT 1002
#define BitmapID1002Bitmap                        1002

//	Resource: PICT 1011
#define Bitmap                                    1011

//	Resource: PICT 1012
#define Bitmap2                                   1012

//	Resource: PICT 1018
#define Bitmap3                                   1018

//	Resource: PICT 1003
#define BitmapID1003Bitmap                        1003

//	Resource: PICT 1001
#define BitmapID1001Bitmap                        1001

//	Resource: PICT 1013
#define BitmapID1013Bitmap                        1013

//	Resource: PICT 2600
#define BitmapID2600Bitmap                        2600

//	Resource: PICT 2605
#define BitmapID2700Bitmap                        2605

//	Resource: PICT 2610
#define BitmapID2610Bitmap                        2610

//	Resource: PICT 2620
#define BitmapID2620Bitmap                        2620

//	Resource: PICT 2630
#define BitmapID2630Bitmap                        2630

//	Resource: PICT 2640
#define BitmapID2640Bitmap                        2640

//	Resource: PICT 2650
#define BitmapID2650Bitmap                        2650

//	Resource: PICT 2660
#define BitmapID2660Bitmap                        2660

//	Resource: PICT 2670
#define BitmapID2670Bitmap                        2670

//	Resource: PICT 2601
#define BitmapID2601Bitmap                        2601

//	Resource: PICT 1800
#define BitmapID1800Bitmap                        1800

//	Resource: PICT 1801
#define BitmapID1801Bitmap                        1801

//	Resource: PICT 2500
#define BitmapID2500Bitmap                        2500

//	Resource: PICT 2800
#define BitmapID2800Bitmap                        2800

//	Resource: PICT 3200
#define BitmapID3200Bitmap                        3200

//	Resource: PICT 3300
#define BitmapID3300Bitmap                        3300

//	Resource: PICT 2501
#define BitmapID2500Bitmap2                       2501

//	Resource: PICT 2801
#define BitmapID2800Bitmap2                       2801

//	Resource: PICT 3201
#define BitmapID3200Bitmap2                       3201

//	Resource: PICT 3301
#define BitmapID330Bitmap                         3301

//	Resource: PICT 2300
#define BitmapID2300Bitmap                        2300

//	Resource: PICT 2301
#define BitmapID2300Bitmap2                       2301


//	Resource: tbmf 2600
#define CarColorBitmapFamily                      2600

//	Resource: tbmf 2605
#define CarColorSliderBitmapFamily                2605

//	Resource: tbmf 2610
#define SingleRaceBitmapFamily                    2610

//	Resource: tbmf 2620
#define ChampionshipBitmapFamily                  2620

//	Resource: tbmf 2630
#define DemoBitmapFamily                          2630

//	Resource: tbmf 2640
#define OptionsBitmapFamily                       2640

//	Resource: tbmf 2650
#define PlayersBitmapFamily                       2650

//	Resource: tbmf 2660
#define PlayerBitmapFamily                        2660

//	Resource: tbmf 2670
#define TracksBitmapFamily                        2670

//	Resource: tbmf 11800
#define Speed_BitmapFamily                        11800

//	Resource: tbmf 12300
#define Lap_BitmapFamily                          12300

//	Resource: tbmf 12500
#define Position_BitmapFamily                     12500

//	Resource: tbmf 12800
#define FinalLap_BitmapFamily                     12800

//	Resource: tbmf 13200
#define Go_BitmapFamily                           13200

//	Resource: tbmf 13300
#define Finish_BitmapFamily                       13300


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

