//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 12:42:38  on 22 Íîÿáðü 2002 ã.
//
//	Generated for file: C:\Work\Palm\Flat3D\Project\Rsc\Graphics.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Untitled"
//
//	Palm App Version:		"1.0"


//	Resource: Talt 5000
#define NeedMoreColorsAlert                       5000
#define NeedMoreColorsCloseApplication            0

//	Resource: Talt 5100
#define COLOR_Alert                               5100
#define COLOR_GRAY                                0


//	Resource: PICT 1100
#define BitmapID1100Bitmap                        1100

//	Resource: PICT 2000
#define BitmapID2000Bitmap                        2000

//	Resource: PICT 1000
#define BitmapID1000Bitmap                        1000

//	Resource: PICT 1300
#define BitmapID1300Bitmap                        1300

//	Resource: PICT 1200
#define BitmapID1200Bitmap                        1200

//	Resource: PICT 1500
#define BitmapID1500Bitmap                        1500

//	Resource: PICT 1201
#define BitmapID1201Bitmap                        1201

//	Resource: PICT 1202
#define BitmapID1202Bitmap                        1202

//	Resource: PICT 1203
#define BitmapID1203Bitmap                        1203

//	Resource: PICT 1204
#define BitmapID1204Bitmap                        1204

//	Resource: PICT 1700
#define BitmapID1700Bitmap                        1700

//	Resource: PICT 1900
#define BitmapID1900Bitmap                        1900

//	Resource: PICT 2100
#define BitmapID2100Bitmap                        2100

//	Resource: PICT 2200
#define BitmapID2200Bitmap                        2200

//	Resource: PICT 2400
#define BitmapID2400Bitmap                        2400

//	Resource: PICT 2900
#define BitmapID2900Bitmap                        2900

//	Resource: PICT 3000
#define BitmapID3000Bitmap                        3000

//	Resource: PICT 3100
#define BitmapID3100Bitmap                        3100

//	Resource: PICT 3400
#define BitmapID3400Bitmap                        3400

//	Resource: PICT 1600
#define BitmapID1600Bitmap                        1600


//	Resource: tbmf 3400
#define RotateBackBitmapFamily                    3400

//	Resource: tbmf 1700
#define FPSBitmapFamily                           1700

//	Resource: tbmf 1600
#define NumbersBitmapFamily                       1600

//	Resource: tbmf 1204
#define Water4BitmapFamily                        1204

//	Resource: tbmf 1203
#define Water3BitmapFamily                        1203

//	Resource: tbmf 1202
#define Water2BitmapFamily                        1202

//	Resource: tbmf 1201
#define Water1BitmapFamily                        1201

//	Resource: tbmf 1500
#define SandBitmapFamily                          1500

//	Resource: tbmf 1200
#define WaterBitmapFamily                         1200

//	Resource: tbmf 2000
#define BrRoadBitmapFamily                        2000

//	Resource: tbmf 1300
#define GrassJoinBitmapFamily                     1300

//	Resource: tbmf 1000
#define RoadBitmapFamily                          1000

//	Resource: tbmf 1100
#define SkyBitmapFamily                           1100

//	Resource: tbmf 1900
#define SpecialBitmapFamily                       1900

//	Resource: tbmf 2100
#define BridgeBitmapFamily                        2100

//	Resource: tbmf 2200
#define GrassBitmapFamily                         2200

//	Resource: tbmf 2300
#define LapBitmapFamily                           2300

//	Resource: tbmf 2400
#define SmallNumbersBitmapFamily                  2400

//	Resource: tbmf 2500
#define PositionBitmapFamily                      2500

//	Resource: tbmf 2800
#define FinalLapBitmapFamily                      2800

//	Resource: tbmf 2900
#define ThreeBitmapFamily                         2900

//	Resource: tbmf 3000
#define TwoBitmapFamily                           3000

//	Resource: tbmf 3100
#define OneBitmapFamily                           3100

//	Resource: tbmf 3200
#define GoBitmapFamily                            3200

//	Resource: tbmf 3300
#define FinishBitmapFamily                        3300

//	Resource: tbmf 1800
#define SpeedBitmapFamily                         1800

